server:
  port: 8082

#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/food_ordering_system
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update  # hoặc validate/create-drop tùy môi trường
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

spring:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:8080/Order_Management
    username: postgres
    password: thaovy03072004.
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers=PLAINTEXT://broker:9090:
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:init-schema.sql
