server:
  port: 8082

spring:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/Order_Management
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

#  kafka:
#    bootstrap-servers=PLAINTEXT://broker:9090:
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:init-schema.sql
