package com.swa.order_service.order_dataaccess.adapter;

import com.swa.order_service.order_dataaccess.entity.OrderEntity;
import com.swa.order_service.order_dataaccess.mapper.OrderJpaMapper;
import com.swa.order_service.order_dataaccess.repository.OrderJpaRepository;
import com.swa.order_service.order_domain.order_application_service.ports.output.OrderRepository;
import com.swa.order_service.order_domain.order_domain_core.entity.Order;
import org.springframework.stereotype.Service;

@Service
public class OrderRepositoryImpl implements OrderRepository {
    //JPARepository-generated by SpringData
    private final OrderJpaRepository orderJpaRepository;
    //Mapper:DomainEntity<->JPAEntity
    private final OrderJpaMapper mapper;

    public OrderRepositoryImpl(OrderJpaRepository orderJpaRepository, OrderJpaMapper mapper) {
        this.orderJpaRepository = orderJpaRepository;
        this.mapper = mapper;
    }

    /**
     *ADAPTERPATTERN
     *
     *Transformations:
     *DomainOrder->JPAOrderEntity->Database
     *Database->JPAOrderEntity->DomainOrder
     */
    @Override
    public Order save(Order order){
        //Step1:Domain->JPAEntity
        OrderEntity orderEntity=mapper
                .orderToOrderEntity(order);
        //Step2:Save to database
        OrderEntity savedEntity=orderJpaRepository.save(orderEntity);
        //Step3:JPAEntity->Domain
        return mapper
                .orderEntityToOrder(savedEntity);
    }
//    @Override
//    public Optional<Order>findById(OrderId orderId){
//        return orderJpaRepository
//                .findById(orderId.getValue())
//                .map(orderDataAccessMapper::orderEntityToOrder);
//    }
//
//    @Override
//    public Optional<Order>findByTrackingId(TrackingId trackingId){
//        return orderJpaRepository
//                .findByTrackingId(trackingId.getValue())
//                .map(orderDataAccessMapper::orderEntityToOrder);
//    }
}
